[build]
default-target = "x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl.dockerfile]
file = "cross/Dockerfile.musl"

[target.x86_64-unknown-linux-musl.dockerfile]
file = "cross/Dockerfile.musl"

[target.aarch64-unknown-linux-gnu.dockerfile]
file = "cross/Dockerfile.gnu"

[target.x86_64-unknown-linux-gnu.dockerfile]
file = "cross/Dockerfile.gnu"
