[package]
name = "containerd-shim-wasmedge"
version.workspace = true
edition.workspace = true

[dependencies]
containerd-shim = { workspace = true }
containerd-shim-wasm = { workspace = true, features = ["libcontainer"]}
log = { workspace = true }
ttrpc = { workspace = true }
wasmedge-sdk = { version = "0.11.2" }
wasmedge-sys = "*"
chrono = { workspace = true }
anyhow = { workspace = true }
cap-std = { workspace = true }
oci-spec = { workspace = true, features = ["runtime"] }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
nix = { workspace = true }
libc = { workspace = true }
libcontainer = { workspace = true }
dbus = { version = "*", optional = true }

[dev-dependencies]
tempfile = "3.7"
pretty_assertions = "1"
serial_test = "*"

[features]
default = ["standalone", "static"]
standalone = ["wasmedge-sdk/standalone"]
static = ["wasmedge-sdk/static"]
wasi_nn = ["wasmedge-sdk/wasi_nn"]
vendored_dbus = ["dbus/vendored"]

[[bin]]
name = "containerd-shim-wasmedge-v1"
path = "src/bin/containerd-shim-wasmedge-v1/main.rs"

[[bin]]
name = "containerd-shim-wasmedged-v1"
path = "src/bin/containerd-shim-wasmedged-v1/main.rs"

[[bin]]
name = "containerd-wasmedged"
path = "src/bin/containerd-wasmedged/main.rs"
