[package]
name = "containerd-shim-wasmer"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
containerd-shim = { workspace = true }
containerd-shim-wasm = { workspace = true }
log = { workspace = true }
oci-spec = { workspace = true, features = ["runtime"] }
ttrpc = { workspace = true }

tokio = "1.33.0"
wasmer = { version = "4.1.2" }
wasmer-compiler = { version = "4.1.2", features = ["compiler"] }
wasmer-wasix = { version = "0.12.0" }

[dev-dependencies]
containerd-shim-wasm = { workspace = true, features = ["testing"] }
serial_test = "2"

[[bin]]
name = "containerd-shim-wasmer-v1"
path = "src/main.rs"
