name: Run end to end tests on kind

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      runtime:
        required: true
        type: string

jobs:
  e2e-kind:
    name: e2e kind test on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup build env
        run: ./scripts/setup-linux.sh
        shell: bash
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: containerd-shim-${{ inputs.runtime }}-linux-musl
          path: dist
      - name: Unpack artifats
        shell: bash
        run: |
          mkdir -p dist/bin
          tar -xzf dist/containerd-shim-${{ inputs.runtime }}-linux-musl.tar.gz -C dist/bin
      - name: Download test image
        uses: actions/download-artifact@master
        with:
          name: test-image
          path: dist
      - name: run
        timeout-minutes: 5
        run: make test/k8s-${{ inputs.runtime }}
      # only runs when the previous step fails
      - name: inspect failed pods
        if: failure()
        run: |
          kubectl get pods --all-namespaces
          kubectl describe pods --all-namespaces
      - name: tar logs
        if: failure()
        run: |
          bin/kind export logs ./kind-logs --name containerd-wasm
          tar czf kind-logs-${{ inputs.runtime }}-${{ inputs.os }}.tar.gz -C ./kind-logs .
      - name: upload logs
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: kind-logs-${{ inputs.runtime }}-${{ inputs.os }}
          path: kind-logs-${{ inputs.runtime }}-${{ inputs.os }}.tar.gz
      - name: cleanup
        if: always()
        run: make test/k8s/clean
